### ISSUE TITLE
Message Monitor Console broke

### ISSUE THREAD

**Issue by Galdar02** [citadel-station/citadel-main#13716]
Got told by the window to send this here, so here it is

TypeError: Unable to get property 'getState' of undefined or null reference
   at t.useBackend (http://127.0.0.1:50126/tmp13964/tgui-common.chunk.js:1:4908)
   at l (http://127.0.0.1:50126/tmp13964/tgui.bundle.js:1:553406)
   at Anonymous function (http://127.0.0.1:50126/tmp13964/tgui-common.chunk.js:1:220076)
   at Anonymous function (http://127.0.0.1:50126/tmp13964/tgui-common.chunk.js:1:220046)
   at Te (http://127.0.0.1:50126/tmp13964/tgui-common.chunk.js:1:220024)
   at Me (http://127.0.0.1:50126/tmp13964/tgui-common.chunk.js:1:221160)
   at Anonymous function (http://127.0.0.1:50126/tmp13964/tgui-common.chunk.js:1:220354)
   at Te (http://127.0.0.1:50126/tmp13964/tgui-common.chunk.js:1:220222)
   at Me (http://127.0.0.1:50126/tmp13964/tgui-common.chunk.js:1:221160)
   at Anonymous function (http://127.0.0.1:50126/tmp13964/tgui-common.chunk.js:1:220354)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"galdar02","interface":"TelecommsPDALog","window":{"key":"[0x200fe17]-main","size":null,"fancy":1,"locked":1}}

**Comment by Sonic121x** [comment]
#13379
